/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  safelist: [
    'text-teal-500',
    'text-purple-500',
    'text-blue-500',
    'text-rose-500',
    'bg-teal-500',
    'bg-purple-500',
    'bg-blue-500',
    'bg-rose-500',
    'hover:bg-teal-600',
    'hover:bg-purple-600',
    'hover:bg-blue-600',
    'hover:bg-rose-600',
    'border-teal-500',
    'border-purple-500',
    'border-blue-500',
    'border-rose-500',
    'text-teal-700',
    'text-purple-700',
    'text-blue-700',
    'text-rose-700',
    'bg-teal-100',
    'bg-purple-100',
    'bg-blue-100',
    'bg-rose-100',
    'text-teal-800',
    'text-purple-800',
    'text-blue-800',
    'text-rose-800',
    'text-teal-200',
    'text-purple-200',
    'text-blue-200',
    'text-rose-200',
    'text-teal-300',
    'text-purple-300',
    'text-blue-300',
    'text-rose-300',
    'bg-teal-50',
    'bg-purple-50',
    'bg-blue-50',
    'bg-rose-50',
    'bg-teal-900/20',
    'bg-purple-900/20',
    'bg-blue-900/20',
    'bg-rose-900/20',
    'bg-teal-900/10',
    'bg-purple-900/10',
    'bg-blue-900/10',
    'bg-rose-900/10'
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        fadeIn: 'fadeIn 1s ease-in-out',
        slideUp: 'slideUp 0.8s ease-in-out',
        blink: 'blink 1s step-end infinite',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
      },
      transitionProperty: {
        'height': 'height',
        'spacing': 'margin, padding',
      },
    },
  },
  plugins: [],
};